### ISSUE TITLE
Wrong Submission instructions in  https://github.com/ETCE-LAB/teaching-material/blob/master/The-Limits-to-Growth/Exercises/E02-Resource-Scarcity.docx

### ISSUE THREAD

**Issue by lucaspalomodevelop** [ETCE-LAB/teaching-material#24]
in https://github.com/ETCE-LAB/teaching-material/blob/master/The-Limits-to-Growth/Exercises/E02-Resource-Scarcity.docx

the Submission instructions should read 
`e.g.: “E02-Your_Name.pdf"` not `e.g.: "E03-Your_Name.pdf"`

**Comment by xenomorph1096** [comment]
Thanks for reporting this, it is fixed now?
